LIB_SRC = EventLoop.cpp Channel.cpp Poller.cpp NetAddr.cpp Socket.cpp SocketUtil.cpp Acceptor.cpp TcpServer.cpp TcpConnection.cpp 
BINARIES = test0 test1 test2 test3 test4

all: $(BINARIES)

include ../reactor.mk

test0: test0.cpp
test1: test1.cpp
test2: test2.cpp
test3: test3.cpp
test4: test4.cpp