LIB_SRC = Channel.cpp EventLoop.cpp Poller.cpp Timer.cpp TimerQueue.cpp
BINARIES = test0 test1 test2 test3

all: $(BINARIES)

include ../reactor.mk

test0: test0.cpp
test1: test1.cpp
test2: test2.cpp
test3: test3.cpp