LIB_SRC = EventLoop.cpp Channel.cpp Poller.cpp Timer.cpp TimerManager.cpp
BINARIES = test3

all: $(BINARIES)

include ../reactor.mk

test0: test0.cpp
test1: test1.cpp
test2: test2.cpp
test3: test3.cpp