LIB_SRC = EventLoop.cpp Channel.cpp Poller.cpp Acceptor.cpp IOThread.cpp\
		Timer.cpp TimerManager.cpp Buffer.cpp Socket.cc SocketsOps.cc InetAddress.cc TcpServer.cpp TcpConn.cpp \

BINARIES = test8

all: $(BINARIES)

include ../reactor.mk

test0: test0.cpp
test1: test1.cpp
test2: test2.cpp
test3: test3.cpp
test4: test4.cpp
test5: test5.cpp
test6: test6.cpp
test7: test7.cpp
test8: test8.cpp